# The PMOD GPIO
set_property IOSTANDARD LVCMOS18 [get_ports {pmod_tri_o[*]}]
set_property PACKAGE_PIN G2 [get_ports {pmod_tri_o[0]}]	
set_property PACKAGE_PIN F2 [get_ports {pmod_tri_o[1]}]	
set_property PACKAGE_PIN G3 [get_ports {pmod_tri_o[2]}]	
set_property PACKAGE_PIN F3 [get_ports {pmod_tri_o[3]}]	
set_property PACKAGE_PIN E2 [get_ports {pmod_tri_o[4]}]	
set_property PACKAGE_PIN E1 [get_ports {pmod_tri_o[5]}]	
set_property PACKAGE_PIN F4 [get_ports {pmod_tri_o[6]}]	
set_property PACKAGE_PIN E4 [get_ports {pmod_tri_o[7]}]	
set_property PACKAGE_PIN D2 [get_ports {pmod_tri_o[8]}]	
set_property PACKAGE_PIN D1 [get_ports {pmod_tri_o[9]}]	
set_property PACKAGE_PIN A3 [get_ports {pmod_tri_o[10]}]	
set_property PACKAGE_PIN A2 [get_ports {pmod_tri_o[11]}]	
set_property PACKAGE_PIN C1 [get_ports {pmod_tri_o[12]}]	
set_property PACKAGE_PIN B1 [get_ports {pmod_tri_o[13]}]	
set_property PACKAGE_PIN H4 [get_ports {pmod_tri_o[14]}]	
set_property PACKAGE_PIN H3 [get_ports {pmod_tri_o[15]}]	

